Implement Jest testing platform for all exercises (Solutions branch)
TheOdinProject/javascript-exercises pull request #148
Opened 2021-05-11 03:47 UTC by xandora

This PR overhauls the JavaScript exercises to use Jest instead of Jasmine. This is the Solutions branch version, and should be identical except for the implemented solutions.

- Updated README.md content.
- Updated syntax to be consistent across exercises.
- Users can simply `npm install` to pull required node modules in using `package.json` file.
- ESLint has been included, but is set to run manually as a forward thinking possibility for a "Linting lesson" using existing lessons.

2021-05-11 21:53 UTC, twalton83 requested changes
Just a couple small things!

2021-05-11 21:53 UTC, twalton83 commented on helloWorld/helloWorld.spec.js
> +});
Can we have a new line?

2021-05-11 21:53 UTC, twalton83 commented on pigLatin/pigLatin.js
> +  module.exports = pigLatin;
Another new line.

2021-05-12 09:41 UTC, xandora commented on helloWorld/helloWorld.spec.js
> +});
Done.

2021-05-12 09:41 UTC, xandora commented on pigLatin/pigLatin.js
> +  module.exports = pigLatin;
Done.

2021-05-13 01:47 UTC, twalton83 commented
Closing because this will be addressed with #150 instead

2021-05-13 01:47 UTC, closed without merging