Exercise 2: Add solution that uses built-in method
TheOdinProject/javascript-exercises pull request #460
Opened 2024-05-03 02:04 UTC by nikitarevenco

I feel like learners at this stage are likely to use a for loop so they may find it interesting to know that there is a built-in way of doing it. Of course just using it as the solution would defeat the point of the exercise so I've added it as a second solution

2024-06-29 15:12 UTC, MaoShizhong commented
I'm hesitant on this one.

I believe the intention of the exercise is to get learners to get more practice with using loops. The hint quite firmly suggests this, but I feel for the exercise's intent, if loops are what it wants the learner to practise, it would be better placed in the actual exercise instructions instead of the hints section.

Basically saying that even though there is a built in string method for repeating strings, we want to practise loops so do it manually with loops instead. That way, they're also made aware of the string method.

2024-08-09 17:57 UTC, nikitarevenco commented
> I'm hesitant on this one.
> 
> I believe the intention of the exercise is to get learners to get more practice with using loops. The hint quite firmly suggests this, but I feel for the exercise's intent, if loops are what it wants the learner to practise, it would be better placed in the actual exercise instructions instead of the hints section.
> 
> Basically saying that even though there is a built in string method for repeating strings, we want to practise loops so do it manually with loops instead. That way, they're also made aware of the string method.

I've repurposed this PR

2024-08-10 16:09 UTC, MaoShizhong requested changes

2024-08-10 16:09 UTC, MaoShizhong commented on 02_repeatString/README.md
Thanks for this. Mind removing the "You're going to want to use a loop for this one." hint as it's now redundant? The rest can be left as is.

2024-08-10 16:25 UTC, nikitarevenco commented on 02_repeatString/README.md
Ok, I removed it

2024-08-10 16:59 UTC, MaoShizhong approved these changes

2024-08-10 17:00 UTC, merged