02_repeatString - Line-32, replace "odin" with "hey"
TheOdinProject/javascript-exercises pull request #505
Opened 2024-11-13 14:10 UTC by bhagyeshsp

The original code had "hey" as the seed string value and hence the comment on line-29 mentions "hey". But the last commit on the code changed "hey" to "odin".

We can either change instances of comment or the code. I propose changing the code instance from "odin" to "hey" for consistency.

## Because

There is an inconsistency between the comment on line-29 and its corresponding code on line-32. It provides clarity to the learner by maintaining the same example of "hey" instead of "odin".

## This PR

- Replaced two instances of "odin" with "hey" on line-32

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR includes any changes that affect the solution of an exercise, I've also updated the solution in the `/solutions` folder

2024-11-14 12:37 UTC, MaoShizhong commented
In #460 the instructions were made clear that `String.prototype.repeat` should not be used and the implementation should be done manually via loops. I wonder if the team would agree that on top of fixing the `'hey'` thing, the test be changed to 
```js
expect(repeatString('hey', number)).toBe('hey'.repeat(number));
```

Then the big regex explanation comment can be removed.

2024-11-15 07:03 UTC, bhagyeshsp commented
> In #460 the instructions were made clear that `String.prototype.repeat` should not be used and the implementation should be done manually via loops. 

Thanks, I saw #460  I'm unsure how it is related to this PR.
The current PR is more content-specific than code-specific.

> I wonder if the team would agree that on top of fixing the `'hey'` thing, the test be changed to
> 
> ```js
> expect(repeatString('hey', number)).toBe('hey'.repeat(number));
> ```
> 
The test has been already changed to its present form since August, 2024 under #460 
This PR proposes getting the comment, code and example in alignment by maintaining "hey" throughout.


> Then the big regex explanation comment can be removed.

I found the regex explanation educational.

2024-11-15 09:53 UTC, MaoShizhong commented
My comment was more an addition to yours and directed at the team when they review as opposed to directed at you, sorry if that wasn't clear. Regex was previously removed from comments and solutions in some of these exercises due to it being rather out of scope for this part of the curriculum. Hence the suggestion to the team that while we're at it, it may be best to apply the same approach here.

2025-02-03 00:07 UTC, JoshDevHub requested changes
@bhagyeshsp This seems like a good change to me. Sorry it took us a while to look at it.

I have one change to request: the [solutions test](https://github.com/TheOdinProject/javascript-exercises/blob/main/02_repeatString/solution/repeatString-solution.spec.js) needs to make this same change. Would you be able to add a commit that changes it there as well?

2025-02-03 00:10 UTC, JoshDevHub commented
@MaoShizhong I also think what you've said on this makes sense. Feel free to make a PR (or an issue if you don't want to work on it) that removes regex and uses `String.prototype.repeat`

2025-02-03 04:32 UTC, bhagyeshsp commented
> @bhagyeshsp This seems like a good change to me. Sorry it took us a while to look at it.
> 
> I have one change to request: the [solutions test](https://github.com/TheOdinProject/javascript-exercises/blob/main/02_repeatString/solution/repeatString-solution.spec.js) needs to make this same change. Would you be able to add a commit that changes it there as well?

Hi @JoshDevHub, implemented the commit in the requested solution too.

2025-02-03 22:35 UTC, JoshDevHub approved these changes
You could have just added the commit to this PR instead of opening a new one, but that's okay. Something for you to keep in mind in the future :thumbsup:

2025-02-03 22:35 UTC, merged

2025-02-04 02:52 UTC, bhagyeshsp commented
> You could have just added the commit to this PR instead of opening a new one, but that's okay. Something for you to keep in mind in the future 👍

Oh, I will keep that in mind in the future. Still learning the nitty-gritty.
Thanks for considering the merge.